USE [master]
GO
/****** Object:  Database [ApiEnocaDb]    Script Date: 17.03.2025 11:54:44 ******/
CREATE DATABASE [ApiEnocaDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ApiEnocaDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ApiEnocaDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ApiEnocaDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ApiEnocaDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [ApiEnocaDb] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ApiEnocaDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ApiEnocaDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ApiEnocaDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ApiEnocaDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ApiEnocaDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ApiEnocaDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [ApiEnocaDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ApiEnocaDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ApiEnocaDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ApiEnocaDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ApiEnocaDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ApiEnocaDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ApiEnocaDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ApiEnocaDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ApiEnocaDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ApiEnocaDb] SET  ENABLE_BROKER 
GO
ALTER DATABASE [ApiEnocaDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ApiEnocaDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ApiEnocaDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ApiEnocaDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ApiEnocaDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ApiEnocaDb] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [ApiEnocaDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ApiEnocaDb] SET RECOVERY FULL 
GO
ALTER DATABASE [ApiEnocaDb] SET  MULTI_USER 
GO
ALTER DATABASE [ApiEnocaDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ApiEnocaDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ApiEnocaDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ApiEnocaDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ApiEnocaDb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ApiEnocaDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'ApiEnocaDb', N'ON'
GO
ALTER DATABASE [ApiEnocaDb] SET QUERY_STORE = ON
GO
ALTER DATABASE [ApiEnocaDb] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [ApiEnocaDb]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 17.03.2025 11:54:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CarrierConfigurations]    Script Date: 17.03.2025 11:54:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CarrierConfigurations](
	[CarrierConfigurationsId] [int] IDENTITY(1,1) NOT NULL,
	[CarrierMaxDesi] [int] NOT NULL,
	[CarrierMinDesi] [int] NOT NULL,
	[CarrierCost] [decimal](18, 2) NOT NULL,
	[carriersId] [int] NOT NULL,
 CONSTRAINT [PK_CarrierConfigurations] PRIMARY KEY CLUSTERED 
(
	[CarrierConfigurationsId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Carriers]    Script Date: 17.03.2025 11:54:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Carriers](
	[CarriersId] [int] IDENTITY(1,1) NOT NULL,
	[CarrierName] [nvarchar](max) NOT NULL,
	[CarrrierIsActive] [bit] NOT NULL,
	[CarrierPlusDesiCost] [int] NOT NULL,
	[CarrierConfigurationId] [int] NOT NULL,
 CONSTRAINT [PK_Carriers] PRIMARY KEY CLUSTERED 
(
	[CarriersId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Orders]    Script Date: 17.03.2025 11:54:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Orders](
	[OrdersId] [int] IDENTITY(1,1) NOT NULL,
	[OrderDesi] [int] NOT NULL,
	[OrderDate] [datetime2](7) NOT NULL,
	[OrderCarrierCost] [decimal](18, 2) NOT NULL,
	[carriersId] [int] NOT NULL,
 CONSTRAINT [PK_Orders] PRIMARY KEY CLUSTERED 
(
	[OrdersId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_CarrierConfigurations_carriersId]    Script Date: 17.03.2025 11:54:45 ******/
CREATE NONCLUSTERED INDEX [IX_CarrierConfigurations_carriersId] ON [dbo].[CarrierConfigurations]
(
	[carriersId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Orders_carriersId]    Script Date: 17.03.2025 11:54:45 ******/
CREATE NONCLUSTERED INDEX [IX_Orders_carriersId] ON [dbo].[Orders]
(
	[carriersId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CarrierConfigurations] ADD  DEFAULT ((0)) FOR [carriersId]
GO
ALTER TABLE [dbo].[Orders] ADD  DEFAULT ((0)) FOR [carriersId]
GO
ALTER TABLE [dbo].[CarrierConfigurations]  WITH CHECK ADD  CONSTRAINT [FK_CarrierConfigurations_Carriers_carriersId] FOREIGN KEY([carriersId])
REFERENCES [dbo].[Carriers] ([CarriersId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CarrierConfigurations] CHECK CONSTRAINT [FK_CarrierConfigurations_Carriers_carriersId]
GO
ALTER TABLE [dbo].[Orders]  WITH CHECK ADD  CONSTRAINT [FK_Orders_Carriers_carriersId] FOREIGN KEY([carriersId])
REFERENCES [dbo].[Carriers] ([CarriersId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Orders] CHECK CONSTRAINT [FK_Orders_Carriers_carriersId]
GO
USE [master]
GO
ALTER DATABASE [ApiEnocaDb] SET  READ_WRITE 
GO
